export const TOPICS = [
  { id: 1, name: "Introduction", to: "/introduction" },
  { id: 2, name: "Execution Context", to: "/execution-context" },
  { id: 3, name: "Scope Chain", to: "/scope-chain" },
  { id: 4, name: "Call Stack", to: "/call-stack" },
  { id: 5, name: "Hoisting", to: "/hoisting" },
  { id: 6, name: "Var, Let, Const", to: "/var-let-const" },
  { id: 7, name: "This Keyword", to: "/this-keyword" },
  { id: 8, name: "Call, Bind, Apply", to: "/call-bind-apply" },
  { id: 9, name: "Closure", to: "/closure" },
  { id: 10, name: "Event Loop", to: "/event-loop" },
  { id: 11, name: "Functions", to: "/functions" },
  { id: 12, name: "Callbacks", to: "/callbacks" },
  { id: 13, name: "Promise", to: "/promise" },
  { id: 14, name: "Async/Await", to: "/async-await" },
  { id: 15, name: "Event", to: "/event" },
  { id: 16, name: "Throttling, Debouncing", to: "/throttling-debouncing" },
  { id: 17, name: "Workers", to: "/workers" },
  { id: 18, name: "DOM, Browser APIs", to: "/dom-browser-api" },
  { id: 19, name: "Object Oriented Programming", to: "/oop" },
  { id: 20, name: "JavaScript Engine", to: "/js-engine" },
  { id: 21, name: "ES6+, ES7+ Features", to: "/es6-es7" },
  { id: 22, name: "Advanced JavaScript", to: "/advanced-javascript" },
];
